on:
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: reehan
        
        steps:
            
           
            - uses: actions/checkout@v4
            - run: sudo groupadd docker
            - run: sudo usermod -aG docker $USER

            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" |sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t reehanruhullah/reehan:tagname .
                docker push reehanrulluah/reehan:tagname