on:
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: sampel
        
        steps:
            
            - uses: actions/checkout@v4
            
            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t manu100/project:tagname .
                docker push manu100/project:tagname
                
                
            
            


