
on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: 
          - self-hosted
          - ubuttt
        steps:
          
            - uses: actions/checkout@v4

            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | sudo  docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t reehanruhullah/dataphion_prac:weather .
                docker push reehanruhullah/dataphion_prac:weather