
on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: 
          - self-hosted
          - ubuttt
        

        steps:
            - uses: actions/checkout@v4
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
            - name: Build Docker image
              run: |
               docker image build -t reehanruhullah/dataphion_prac:weather .
             
          
            - name: Push Docker image
              run: |
                 docker push reehanruhullah/dataphion_prac:weather
             
          